# Generated by Django 5.2.3 on 2025-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebeard_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
