# Generated by Django 5.2.3 on 2025-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebeard_tests', '0002_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subgroup_unit',
            field=models.ManyToManyField(related_name='subgroup_unit', to='treebeard_tests.subgroupunit'),
        ),
    ]
